-- 문제 3: 연령대별 집중도 분석
-- 2023년 4월 기준 각 연령대별로 "해당 연령대의 인구수가 전국 연령대별 인구의 집중된 비율 읍/면/동 TOP 3"을 찾으시오
-- 읍면동 연령대 인구 비율 / 전국 연령대 인구별 비율


WITH
KOREA_POP AS (
    SELECT
         AGRDE_SE_CD
        , SUM(POPLTN_CNT) CITY_TOTAL_POP
    FROM TB_POPLTN
    WHERE
        STD_MT='202304'
        AND ADMINIST_ZONE_NO LIKE '__00000000'
        AND POPLTN_SE_CD = 'T'
    GROUP BY
        AGRDE_SE_CD
)
, LOCAL_POP AS (
SELECT ADMINIST_ZONE_NO
     , ADMINIST_ZONE_NM
     , tp.AGRDE_SE_CD
     , SUM(POPLTN_CNT) LOCAL_TOTAL_POP
FROM TB_POPLTN tp
WHERE
    STD_MT = '202304'
    AND ADMINIST_ZONE_NO NOT LIKE '_____00000'
    AND POPLTN_SE_CD = 'T'
    GROUP BY
        ADMINIST_ZONE_NO
        , ADMINIST_ZONE_NM
        , AGRDE_SE_CD
)
, CALC_POP AS (
    SELECT
    ADMINIST_ZONE_NM
   , lp.AGRDE_SE_CD
   , lp.LOCAL_TOTAL_POP / kp.CITY_TOTAL_POP RATE
   , RANK () OVER (PARTITION BY lp.AGRDE_SE_CD ORDER BY (lp.LOCAL_TOTAL_POP / kp.CITY_TOTAL_POP) DESC) RNK
   , lp.LOCAL_TOTAL_POP
   , kp.CITY_TOTAL_POP
    FROM
    KOREA_POP kp
   , LOCAL_POP lp
    WHERE
    lp.AGRDE_SE_CD = kp.AGRDE_SE_CD
    AND kp.CITY_TOTAL_POP > 0
    )
, CALC_RANK AS(
    SELECT
    AGRDE_SE_CD
    , RNK
    , ADMINIST_ZONE_NM
    , RATE
FROM CALC_POP
WHERE RNK <= 3
ORDER BY AGRDE_SE_CD, RNK ASC
    )
SELECT
    cr.AGRDE_SE_CD
    , cr.ADMINIST_ZONE_NM
    , RANK() over (order by RATE DESC ) REAL_RANK
FROM CALC_RANK cr
ORDER BY REAL_RANK







# GROUP BY
#     ADMINIST_ZONE_NO
#     , ADMINIST_ZONE_NM
# ORDER BY ADMINIST_ZONE_NO, lp.AGRDE_SE_CD ASC
;



SELECT
     AGRDE_SE_CD
    , SUM(POPLTN_CNT) CITY_TOTAL_POP
FROM TB_POPLTN
WHERE
    STD_MT='202304'
    AND ADMINIST_ZONE_NO LIKE '__00000000'
    AND POPLTN_SE_CD = 'T'
GROUP BY
    AGRDE_SE_CD
;