-- 문제 4: 10대 vs 60대 비율 비교
-- 2023년 4월 기준 각 읍/면/동별 총 인구수 대비 10대 인구의 비율과 60대 인구의 비율을 구하고,
-- 10대 비율이 60대 비율의 3배 이상인 "청년 집중 지역"을 찾으시오.
WITH REGION_POP AS (
	SELECT
		ADMINIST_ZONE_NO,
        ADMINIST_ZONE_NM,
        SUM(POPLTN_CNT) AS TOT_POP
	FROM TB_POPLTN
    WHERE STD_MT = '202304'
		AND ADMINIST_ZONE_NO NOT LIKE '_____00000'
        AND POPLTN_CNT > 0
	GROUP BY ADMINIST_ZONE_NO, ADMINIST_ZONE_NM
),

AGE_POP AS (
	SELECT
		ADMINIST_ZONE_NO,
        AGRDE_SE_CD,
        SUM(POPLTN_CNT) AS AGE_POP
    FROM TB_POPLTN
    WHERE STD_MT = '202304'
		AND ADMINIST_ZONE_NO NOT LIKE '_____00000'
        AND AGRDE_SE_CD IN ('010', '060')
        AND POPLTN_CNT > 0
	GROUP BY ADMINIST_ZONE_NO, AGRDE_SE_CD
),

AGE_POP_PIVOT AS (
	SELECT
		ADMINIST_ZONE_NO,
        MAX(CASE WHEN AGRDE_SE_CD = '010' THEN AGE_POP ELSE 0 END) AS TEEN_POP,
        MAX(CASE WHEN AGRDE_SE_CD = '060' THEN AGE_POP ELSE 0 END) AS SIXTY_POP
    FROM AGE_POP
    GROUP BY ADMINIST_ZONE_NO
)

SELECT
	r.ADMINIST_ZONE_NO,
	r.ADMINIST_ZONE_NM,
    a.TEEN_POP,
    a.SIXTY_POP,
    r.TOT_POP,
    TEEN_POP / NULLIF(r.TOT_POP, 0) AS TEEN_RATIO,
    SIXTY_POP / NULLIF(r.TOT_POP, 0) AS SIXTY_RATIO
FROM REGION_POP r
JOIN AGE_POP_PIVOT a ON r.ADMINIST_ZONE_NO = a.ADMINIST_ZONE_NO
WHERE (TEEN_POP / NULLIF(r.TOT_POP, 0)) >= 3 * (SIXTY_POP / NULLIF(r.TOT_POP, 0))
ORDER BY TEEN_RATIO DESC;
