WITH GENDER_GENERATION_POP AS (
    SELECT
        ADMINIST_ZONE_NO
        , ADMINIST_ZONE_NM
        , AGRDE_SE_CD
        , SUM(CASE WHEN POPLTN_SE_CD = 'M' THEN POPLTN_CNT ELSE 0 END) AS MALE_POP
        , SUM(CASE WHEN POPLTN_SE_CD = 'F' THEN POPLTN_CNT ELSE 0 END) AS FEMALE_POP
    FROM TB_POPLTN
    WHERE
        STD_MT = '202304'
        AND ADMINIST_ZONE_NO NOT LIKE '_____00000'
        AND POPLTN_SE_CD IN ('M', 'F')
    GROUP BY
        ADMINIST_ZONE_NO
        , ADMINIST_ZONE_NM
        , AGRDE_SE_CD
)
, CALC_POP AS (
    SELECT
        ADMINIST_ZONE_NO
        , ADMINIST_ZONE_NM
        , AGRDE_SE_CD
        , MALE_POP
        , FEMALE_POP
        , CASE WHEN FEMALE_POP - MALE_POP > MALE_POP - FEMALE_POP THEN FEMALE_POP - MALE_POP ELSE MALE_POP - FEMALE_POP END AS TOTAL_DIFF
#         , MALE_POP / FEMALE_POP AS MORE_MALE
#         , FEMALE_POP / MALE_POP AS MORE_FEMALE
    FROM
        GENDER_GENERATION_POP
    WHERE
        MALE_POP / FEMALE_POP > 1.5
        OR FEMALE_POP / MALE_POP > 1.5
    GROUP BY
        ADMINIST_ZONE_NO
        , ADMINIST_ZONE_NM
        , AGRDE_SE_CD
#     ORDER BY
#         MALE_POP DESC
#         , FEMALE_POP DESC;
)
SELECT *
FROM CALC_POP
ORDER BY
    TOTAL_DIFF DESC
LIMIT 10;