-- 문제1 : 연령대별 성비 편차가 큰 지역 찾기
-- 2023년 4월 기준 각 읍/면/동에서 연령대별로 남성과 여성의 비율 차이(남성비율 - 여성비율)가 0.1(10%)
-- 이상 나는 연령대가 가장 많은 지역 TOP 5를 찾으시오.

WITH BASE AS (
	SELECT 
		ADMINIST_ZONE_NO,
        ADMINIST_ZONE_NM,
        AGRDE_SE_CD,
        POPLTN_SE_CD,
        SUM(POPLTN_CNT) AS POP_CNT
	FROM TB_POPLTN
    WHERE STD_MT = '202304'
		AND ADMINIST_ZONE_NO NOT LIKE '_____00000'
        AND POPLTN_SE_CD IN ('M', 'F')
        AND POPLTN_CNT > 0
	GROUP BY ADMINIST_ZONE_NO, ADMINIST_ZONE_NM, AGRDE_SE_CD, POPLTN_SE_CD
), 

PIVOTED AS (
	SELECT
		ADMINIST_ZONE_NO,
        ADMINIST_ZONE_NM,
        AGRDE_SE_CD,
        SUM(CASE WHEN POPLTN_SE_CD = 'M' THEN POP_CNT END) AS MALE_CNT,
        SUM(CASE WHEN POPLTN_SE_CD = 'F' THEN POP_CNT END) AS FEMALE_CNT
	FROM BASE
    GROUP BY ADMINIST_ZONE_NO, ADMINIST_ZONE_NM, AGRDE_SE_CD
),

RATIO AS (
	SELECT
		ADMINIST_ZONE_NO,
        ADMINIST_ZONE_NM,
        AGRDE_SE_CD,
        MALE_CNT,
        FEMALE_CNT, 
        MALE_CNT / NULLIF(MALE_CNT + FEMALE_CNT, 0) AS MALE_RATIO,
        FEMALE_CNT / NULLIF(MALE_CNT + FEMALE_CNT, 0) AS FEMALE_RATIO,
        (MALE_CNT / NULLIF(MALE_CNT + FEMALE_CNT, 0)) 
        -
        (FEMALE_CNT / NULLIF(MALE_CNT + FEMALE_CNT, 0)) AS DIFF
	FROM PIVOTED
) 
SELECT
	ADMINIST_ZONE_NO,
    ADMINIST_ZONE_NM,
    COUNT(*) AS AGE_GROUP_DIFF_OVER_10P
FROM RATIO
WHERE DIFF >= 0.1
GROUP BY ADMINIST_ZONE_NO, ADMINIST_ZONE_NM
ORDER BY AGE_GROUP_DIFF_OVER_10P DESC
LIMIT 5;

